stages:
    - build
    - release

variables:
    PDF_NAME: $CI_PROJECT_NAME.pdf
    ARTIFACT_URL: "${CI_PROJECT_URL}/-/jobs/artifacts/job-${CI_JOB_ID}/download?job=build_job"

build_job:
    stage: build
    image: lanolin25/docker-latex:v1.3
    only:
        - master
    script:
        - make artifacts 
        - make clean
        - mv main.pdf ${PDF_NAME}
    artifacts:
        name: "$CI_PROJECT_NAME"
        paths:
            - ${PDF_NAME}

release_job:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    only:
        - master
    needs:
        - job: build_job
          artifacts: true
    script:
        - echo "Publish new release"
    release:
        name: "$CI_PROJECT_NAME Release $CI_COMMIT_TIMESTAMP"
        description: "Build a PDF file from LaTeX source."
        ref: $CI_COMMIT_SHA
        tag_name: "job-$CI_JOB_ID"
        assets:
            links:
                - name: "${PDF_NAME}.zip"
                  url: "${ARTIFACT_URL}"
                  filepath: "/$CI_COMMIT_SHA/${PDF_NAME}"
                  link_type: package