name: Build on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'master'
  workflow_dispatch:

env: 
  DOCKER_IMAGE: 'lanolin25/docker-latex:v1.6'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Pull Docker to local
        run: docker pull ${DOCKER_IMAGE}
      
      - name: Build PDF
        run: docker run --rm -i -v ${PWD}:/build:Z ${DOCKER_IMAGE} sh -c "make build"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            output/report.pdf
            output/report.log
